### ISSUE TITLE
Culling Problems

### ISSUE THREAD

**Issue by mariotime1287** [hzqst/MetaHookSv#10]
![20210620110743_1](https://user-images.githubusercontent.com/69475944/122679152-c8062b80-d1b7-11eb-9ae9-ea7727c1bc16.jpg)

It seems that when r_wsurf_vbo is set to 1, culling is broken and causes terrain that would normally be invisible to render. This can cause lower performance in some areas. I might not be accurately describing this, so I'll let the image speak for itself.

**Comment by hzqst** [comment]
Culling is known to be broken with "r_wsurf_vbo" "1" since BSP node culling is unusable while drawing world as a single batch. btw BSP tree is not a reasonable data structure for modern GPU culling optimization.

A better way to mitigate this problem is to draw sky surface into depthbuffer to make scene behind sky surface being occluded, 

However this may introduce a new problem that entities with huge model flying around sky (such as monster_apache) will also be occluded by "sky".

**Comment by hzqst** [comment]
> ![20210620110743_1](https://user-images.githubusercontent.com/69475944/122679152-c8062b80-d1b7-11eb-9ae9-ea7727c1bc16.jpg)
> 
> It seems that when r_wsurf_vbo is set to 1, culling is broken and causes terrain that would normally be invisible to render. This can cause lower performance in some areas. I might not be accurately describing this, so I'll let the image speak for itself.

Can you have a quick test with commit f331882 ? r_wsurf_sky_occlusion 1 should fix this.

**Comment by mariotime1287** [comment]
It has indeed been fixed.
