### ISSUE TITLE
[Suggestion] ViewModel Source sway effect

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#165]
I found this old MetaHook ViewModel sway effect plugin(check video description).
It looks like it works with MHSv but I thought it could probably cause some problems.
Was wondering if we could get an official updated version of it for all GoldSrc games.
Thank you.
https://www.youtube.com/watch?v=glwu4RRrQxA

https://user-images.githubusercontent.com/3608544/175115029-a30f21e2-be74-4a9c-a7b6-e7dc07e47d8a.mp4

**Comment by hzqst** [comment]
Do you have source code of that plugin? better update from original source code instead of reversed-engineered code or copy-paste code that is taken from [other mods](https://github.com/SNMetamorph/PrimeXT/blob/master/client/r_view.cpp#L266).

Or you can just copy-paste [viewmodellag.cpp from ABCEnchance](https://github.com/DrAbcOfficial/ABCEnchance/blob/3ece53dc213b4dfdfea7ae76dbf89b46e549b035/viewmodellag.cpp#L16) and try to create a simple plugin by yourself.
