### ISSUE TITLE
[Renderer] Radioactive Acid Glitches out in Opposing Force

### ISSUE THREAD

**Issue by Zaphero1** [hzqst/MetaHookSv#227]
The Acid of this room in Opposing Force ends up clipping through the walls. It appears to change depending on where I'm looking or standing so maybe it's an LOD thing. Here's the save file for it.

[Glitched Acid Room.zip](https://github.com/hzqst/MetaHookSv/files/10418683/Glitched.Acid.Room.zip)

![20230114130701_1](https://user-images.githubusercontent.com/19298996/212492660-21459037-6190-4bf3-8c59-9e0bb326e0e9.jpg)
![20230114130705_1](https://user-images.githubusercontent.com/19298996/212492670-1da31a15-c103-4600-803a-7691d6e8687d.jpg)
![20230114130709_1](https://user-images.githubusercontent.com/19298996/212492677-62e64c1d-6342-45bc-a12d-37c5171419b7.jpg)
![20230114130727_1](https://user-images.githubusercontent.com/19298996/212492680-645b38f7-9279-4c0b-b620-8f51ba7630f6.jpg)

**Comment by hzqst** [comment]
That is probably because multiple water entities with different final height but same initial height, same texture and same rendermode are rendered in one batch, causing the unexpected glitch out in your save.

![11](https://user-images.githubusercontent.com/12287588/212834030-d5090709-0130-4cd5-b783-db5b2f098c4f.png)
![22](https://user-images.githubusercontent.com/12287588/212834036-ef715522-d1a8-42a1-afff-fc70d1256c3f.png)

This should have been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230117b

**Comment by Zaphero1** [comment]
Ooo yep looks like that fixed it! Thank you very much!
![20230117022113_1](https://user-images.githubusercontent.com/19298996/212850962-beb5b94c-4512-499d-80bf-6f380981939f.jpg)
