### ISSUE TITLE
[ Engine ] Broken .asi files loading

### ISSUE THREAD

**Issue by ollerjoaco** [hzqst/MetaHookSv#299]
Playing Counter Strike 1.6 I use a FOV fix for playing widescreen.

Repo: https://github.com/Garey27/CS_Patches/releases/tag/0.4.1

With metahook patch dont work and looks like default:
![Counter-Strike 16_07_2023 14_23_38](https://github.com/hzqst/MetaHookSv/assets/57648434/284dfeda-6164-4fbe-b77f-e86a359c1eb2)
With CS_Patches without metahook:
![Counter-Strike 16_07_2023 14_22_20](https://github.com/hzqst/MetaHookSv/assets/57648434/f32a1a6a-e724-4cef-b445-4c34ee93bffd)

**Comment by ollerjoaco** [comment]
For installing CS_Patches you just need to put .asi file in the root folder ( Half-Life ) and it will load automatically.

**Comment by hzqst** [comment]
`Renderer.dll` completely overrides the renderer thus any binary patch to it just won't work.

Are you looking for [r_vertical_fov](https://github.com/hzqst/MetaHookSv/blob/36f95f879a71a01cd3f58391ee3b0781b59cbd3b/Plugins/Renderer/gl_rmain.cpp#L2070) and [viewmodel_fov](https://github.com/hzqst/MetaHookSv/blob/36f95f879a71a01cd3f58391ee3b0781b59cbd3b/Plugins/Renderer/gl_rmain.cpp#L2064)?

**Comment by ollerjoaco** [comment]
Just installed metahook, without the renderer. I was trying to use a Fov
fix which is in the .así file not the MetaRenderer one.

**Comment by hzqst** [comment]
This has nothing to do with .asi files loading mechanism.

The debugger said that the `CS_Fixes.asi` was actually loaded without any problem:
<img width="185" alt="屏幕截图 2024-01-16 114207" src="https://github.com/hzqst/MetaHookSv/assets/12287588/fe8f7f4d-94ea-4c63-a704-8bdecb3e6c5f">

Your issue is probably because the whole renderer was overrided by Renderer.dll, 
The "widescreen fixed" has already be done in the Renderer though. (see [docs](https://github.com/hzqst/MetaHookSv/blob/main/docs/Renderer.md#widescreen-adapted-fov))
