### ISSUE TITLE
mdl collision

### ISSUE THREAD

**Issue by gigirs50** [hzqst/MetaHookSv#307]
hi, collisions on mdl models based on  bullet physic are implemented ? or is it possible to add them? it would be useful for maps since clipnode collisions are very limited

**Comment by hzqst** [comment]
If you are looking for server-side physics: https://github.com/hzqst/metamod-fallguys/blob/main/README_FALLGUYS.md#create-a-physic-object

MetaHookSv/BulletPhysics is only for client-side ragdoll.

**Comment by gigirs50** [comment]
ok thanks great work,it have support for mesh collision or only shapes? is also possible enable hitbox base collision on mdl model?

**Comment by hzqst** [comment]
> ok thanks great work,it have support for mesh collision or only shapes? is also possible enable hitbox base collision on mdl model?

For static objects like world, func_wall, func_door and such stuffs it uses mesh collision. 

For dynamic objects you have to specify a type of shape but you can take advantage of MultiSphere and CompoundShape to build a complex shape.

I have enabled hitbox based collision for most of the dynamic objects in my Fall Guys map except spheres, however it doesn't behave like what you expected:

Hitbox based collision only takes effect in PlayerMove code, which means it only takes effect *when player tries to initiate a movement*. the player movement will be influenced by the hitbox shapes. In the other words, they blocks your movement so that you can stand on top of them but you can't walk through them.

In general you better use the exact same halfextent for hitbox and collision shape.
