### ISSUE TITLE
Metahook virustotal false positives?

### ISSUE THREAD

**Issue by qabRieL99** [hzqst/MetaHookSv#348]
https://www.virustotal.com/gui/file/bf30b022283e7ec91022592174a322df0085b3db1d381f20912d9f831ef202d3

Any idea what's causing it?

**Comment by qabRieL99** [comment]
Older builds were recognized as safer:
https://www.virustotal.com/gui/file/279c6e7ace3f0557bd50b80f27cc09b81125dd5d45f75f8c9a4f029c1e682e7b

**Comment by hzqst** [comment]
> https://www.virustotal.com/gui/file/bf30b022283e7ec91022592174a322df0085b3db1d381f20912d9f831ef202d3
> 
> Any idea what's causing it?

Probably because I added an additional 30MB section for `metahook.exe` to make compatible with blob module (Valve's encrypted engine and client modules back in 2005, which are forced to be loaded at specified virtual address and are loaded as Memory-Payload instead of Windows's LDR-Managed-DLL)

Some retard anti-malwares detect this as memory-payload-execution.

**Comment by JH828** [comment]
Same on Windows Defender, detects trojan. Also, the setup bat fails;
"Setting breakpad minidump AppID = 70
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198022772273 [API loaded no]
\Steam\steamapps\common\Sven was unexpected at this time."

**Comment by qabRieL99** [comment]
The problem is that Windows defender detects it as a virus and removes the file before any installation is made.

**Comment by hzqst** [comment]
https://www.virustotal.com/gui/url/c675ebbe8fdbd323bda43822b82ca0c237ed976f457f1707de25c74fef3e083a

it should be okay now with latest version.

**Comment by qabRieL99** [comment]
It is still marked by 32 vendors. (.exe file)
https://www.virustotal.com/gui/file/fb99409f44c539c63a56270e0549798ed6903f6810fcbedfd1b4b7781f9db3ab
