### ISSUE TITLE
[Renderer] Not supported/freeze and hang at map "lightupthenight-u1"

### ISSUE THREAD

**Issue by Rikunosukee** [hzqst/MetaHookSv#441]
The map called "lightupthenight-u1.bsp" can be found at [here](http://scmapdb.wikidot.com/map:light-up-the-night)

My spec 
AMD Ryzen 3400G RX Vega 11 Graphics
8GB RAM

When i play the map i was freeze in loading probably not supported for renderer here example i capture screnshoot when it freeze

![Screenshot 2024-05-03 010122](https://github.com/hzqst/MetaHookSv/assets/151928131/77fc6be5-b1c7-4834-8b9f-4f5d5bfd8435)

**Comment by hzqst** [comment]
I thought you were running out of VRAM but it should'nt be the case since you are using integrited graphics solution which uses system memory as VRAM. (it could be a Process-Out-of-Memory instead)

This map takes about 2.5 Gigs of VRAM (1.3GB -> 3.9GB):

![image](https://github.com/hzqst/MetaHookSv/assets/12287588/108936bd-3f2e-414f-991c-388186a6e514)
