### ISSUE TITLE
Metahook crashes with OP4

### ISSUE THREAD

**Issue by cidlover** [hzqst/MetaHookSv#93]
For some reason, metahook crashes HL Opposing Force, but others are fine but I can't find the thing crashing my game. I've been working on subtitles for Blue Shift and I think got those done at about 90 ish %, maybe missed something as I need to play through with my dictionary files for english.

I would like to start for OP4 but stuck at just getting the game to stay opened and for me to play with me working on OP4 subs.

Below are the logs if they help any.
[HLOP4_log.zip](https://github.com/hzqst/MetaHookSv/files/7491744/HLOP4_log.zip)

**Comment by hzqst** [comment]
metahook crashes due to missing HUD_GetStudioModelInterface in client dll for op4 (`gearbox/cl_dlls/client.dll`) , null pointer exception is thrown when gExportFuncs.HUD_GetStudioModelInterface is called.

![image](https://user-images.githubusercontent.com/12287588/140632875-06b3c493-a3e7-4e2c-9f9c-ca883c2e87d9.png)
![image](https://user-images.githubusercontent.com/12287588/140632905-80782eb6-c82f-4745-afe0-4cd7dc58247b.png)

e8d9fd8781138cc7d7c8ac05e88d69b885835794 should fix the issue. It deals with this situation (missing client GameStudioRenderer) without problem now.

**Comment by cidlover** [comment]
Downloaded the main zip again to see only OP4, installed with the batch and OP4 now works with metahook so now it works for me to start with the expansion with sub. Thanks for the help and great work so far.
